# Generated by Django 4.1.5 on 2023-02-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camisa_Futbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=60)),
                ('marca', models.CharField(max_length=60)),
                ('año', models.IntegerField()),
                ('valoracion', models.IntegerField()),
                ('reseña', models.TextField(max_length=240)),
                ('imagen', models.ImageField(null=True, upload_to='camisas')),
            ],
        ),
    ]
